name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: setup.cfg
      - name: Install with development dependencies
        run: pip install . -r requirements-dev.txt
      - name: Check with pre-commit
        run: pre-commit run --all-files
      - name: Test
        run: pytest
